import type { NextPage } from "next";
import Head from "next/head";
import Masthead from "@/components/masthead";
import Skills from "@/components/skills";
import Works from "@/components/works";
import useSWR from "swr";
import SelectMetals, {
  getSelectedMetalNumbers,
} from "@/components/select-metals";
import P5jsContainer from "@/components/p5jsContainer";
import { useState } from "react";

const fetcher = (input: any, init?: any) =>
  fetch(input, init).then((res) => res.json());

const Home: NextPage = () => {
  const { data } = useSWR("/api/stats", fetcher);

  // P5jsContainerの表示状態を管理
  const [showP5js, setShowP5js] = useState(false);

  return (
    <div>
      <Head>
        <title>colpoc website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Masthead />
      <Skills commits={data?.commits} downloads={data?.downloads} />
      <Works />
      {/* 金属選択コンポーネント */}
      <SelectMetals onLaunch={() => setShowP5js(true)} />

      {/* ボタンが押されたら表示されるP5jsContainer */}
      {showP5js && <P5jsContainer />}
    </div>
  );
};

export default Home;
